### PR TITLE
Bug scroll to viewport

### PR DESCRIPTION
**Pull request by tung13041996**
This pull request to fixed bug: click to item accordion, window will scroll to viewport.

### CODE REVIEW

**Comment by phucbm** [comment]
I don't understand why "scroll to viewport" is a bug. Could you please explain more? In what case do we need this?

**Comment by phucbm** [comment]
@tung13041996 
Any update on this?

**Comment by tung13041996** [comment]
> @tung13041996 Any update on this?

I will re-check this issue, because of bug in other project(Van Remoortal) when update new version of ETA

**Comment by tung13041996** [comment]
> @tung13041996 Any update on this?

I will update code for this issue because of bug in other project when update to newest version of ETA

**Comment by phucbm** [comment]
@tung13041996 

> I don't understand why "scroll to viewport" is a bug. Could you please explain more? In what case do we need this?

1. You have not answer this question.

> > @tung13041996 Any update on this?
> 
> I will update code for this issue because of bug in other project when update to newest version of ETA

2. I ask for update because I want to know **why did we not close this issue**. Your answer did not help me to make any decision, and I think that you are prolonging. At least give me a deadline.

**Comment by vuquangpham** [comment]
About the `scrollIntoView` method, we make the viewport jump to the wrapper of the target, so that if we scroll to the `last item` of the ETA section, and then we click to the `last item` => the viewport will jump to `the top of the section`, not related to the `last item`.

**Comment by tung13041996** [comment]
@phucbm First, I so sorry for missing notification for this issue. Then, I'll explain why it's a bug.
In all project, trigger is `<a>` with `href=#....`, so function `assignTriggerElements` in `methods.js` will run. So, when we click trigger, line 67 will run and scroll to wrapper. That's the reason I remove line 67.
image

**Comment by phucbm** [comment]
Thank you @tung13041996, it's clear now.

**Review by phucbm — APPROVED** [review]
LGTM.

**Pull request merged**
